### ISSUE TITLE
Error while notifying webhook /tmp/theme.update: No such file or directory @ rb_sysopen - /tmp/theme.update

### ISSUE THREAD

**Issue by haroldao** [montalvomiguelo/shopify-plugin-livereload#1]
Hey @montalvomiguelo!

After following all instructions, I've the following error in my terminal:
![image](https://github.com/montalvomiguelo/shopify-livereload/assets/36776278/8037c850-eb4e-4272-a82e-4cc834110e11)

**Comment by montalvomiguelo** [comment]
Hi @haroldao, Could we check if the directory /tmp/ exists?

**Comment by haroldao** [comment]
No, it doesn't exist

**Comment by montalvomiguelo** [comment]
Let's create the directory please (:

**Comment by haroldao** [comment]
Same issue (even with theme.update inside)
![image](https://github.com/montalvomiguelo/shopify-livereload/assets/36776278/e5ed2f13-5241-4ccc-b4db-62751619139b)

**Comment by montalvomiguelo** [comment]
`/` is the root directory.
You can update the path in the notify flag if you want to notify another file path. Then be sure livereload watches that path.
_e.g. per your screenshot_ `shopify theme dev --notify ./tmp/theme.update`
https://shopify.dev/docs/themes/tools/cli/commands#dev
